
# config/database.yml

# --- 開発／テスト用（SQLite） ---
sqlite_default: &sqlite_default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  primary:
    <<: *sqlite_default
    database: storage/development.sqlite3

test:
  primary:
    <<: *sqlite_default
    database: storage/test.sqlite3

# --- 本番用（PostgreSQL：RenderのDATABASE_URLを使用） ---
pg_default: &pg_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

production:
    primary: &primary_production
        <<: *default
        url: <%= ENV["DATABASE_URL"] %>
    cache:
        <<: *primary_production
    queue:
        <<: *primary_production
    cable:
        <<: *primary_production


