# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#

# config/database.yml

default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# 本番は Render の環境変数 DATABASE_URL（PostgreSQL）を使う

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  #   primary と同じ接続に向けて起動させる（後で削除してOK）
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

# ★ Action Cable（solid_cable）を使うなら、cable ロールも primary に寄せる
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
